import { useCallback } from 'react'
import type { AppStateData } from './use-app-state-data'
import type { AppStateRefs } from './use-app-state-refs'
import type { AppStateRequest } from './use-app-state-request'
import type { AppStateUI } from './use-app-state-ui'
import type { ReaderSidebarState } from './use-reader-sidebar-state'
import type { SourceContextMenuController } from './use-source-context-menu'
import type { SourcesIndex } from './use-sources-index'
import { useFeedBriefingActions } from './use-feed-briefing-actions'
import { useReaderArticleActions } from './use-reader-article-actions'
import { useReaderDataController } from './use-reader-data-controller'
import { useReaderFeatureDerived } from './use-reader-feature-derived'
import { useReaderFeatureEffects } from './use-reader-feature-effects'
import { useReaderFilterControls } from './use-reader-filter-controls'
import { useReaderSessionActions } from './use-reader-session-actions'
import { useReaderSidebarControls } from './use-reader-sidebar-controls'
import { useReaderViewActions } from './use-reader-view-actions'
import { useSummaryArticleState } from './use-summary-article-state'
import { useSummaryTaskActions } from './use-summary-task-actions'
import { useSummaryTaskStripActions } from './use-summary-task-strip-actions'
import {
  readMarkMinScrollProgress,
} from '../lib/app-domain'
import {
  buildCompactTitleParts,
  formatReplyCount,
  formatTimeAgo,
  formatTimeAgoCompact,
  maxStoredFavoriteArticles,
  maxStoredReadArticles,
  normalizeImageURL,
  normalizeSourceKind,
  parseSourceIDFilter,
  plainText,
  sourceTagList,
  toggleFavoriteArticleID,
  toErrorMessage,
  truncate,
  upsertReadArticleID,
} from '../lib/app-utils'

type UseReaderFeatureSectionParams = {
  refs: AppStateRefs
  data: AppStateData
  request: AppStateRequest
  ui: AppStateUI
  sidebarState: ReaderSidebarState
  sourcesIndex: SourcesIndex
  sourceContext: SourceContextMenuController
}

export function useReaderFeatureSection({
  refs,
  data,
  request,
  ui,
  sidebarState,
  sourcesIndex,
  sourceContext,
}: UseReaderFeatureSectionParams) {
  const {
    floatingDetailRef,
    feedAIMoreRef,
    feedBriefingCacheAttemptedRef,
    sidebarSourceItemRefs,
    feedAutoLoadRef,
    sidebarTagFilterTimerRef,
    feedAutoLoadCooldownRef,
    streamScrollYRef,
    feedRequestSeqRef,
    articleRequestSeqRef,
    summaryRequestSeqRef,
  summaryTaskNotifiedRef,
  readerSessionRef,
  } = refs
  const {
    sources,
    setSources,
    feed,
    setFeed,
    selectedArticle,
    setSelectedArticle,
    selectedArticleID,
    setSelectedArticleID,
    articleSummary,
    setArticleSummary,
    articleSummaryMeta,
    setArticleSummaryMeta,
    summaryTasks,
    setSummaryTasks,
    loadingArticleSummary,
    setLoadingArticleSummary,
    articleSummaryError,
    setArticleSummaryError,
    feedBriefing,
    setFeedBriefing,
    feedBriefingMeta,
    setFeedBriefingMeta,
    feedBriefingItems,
    setFeedBriefingItems,
    feedBriefingArticleCount,
    setFeedBriefingArticleCount,
    feedBriefingScopeLabel,
    setFeedBriefingScopeLabel,
    feedBriefingGeneratedAt,
    setFeedBriefingGeneratedAt,
    feedBriefingAnchorArticleIDs,
    setFeedBriefingAnchorArticleIDs,
    feedBriefingTaskKey,
    setFeedBriefingTaskKey,
    feedBriefingSnapshots,
    setFeedBriefingSnapshots,
    loadingFeedBriefing,
    setLoadingFeedBriefing,
    feedBriefingError,
    setFeedBriefingError,
    aiModel,
    setAIModel,
    sourceStatus,
    setSourceStatus,
    readArticleIDs,
    setReadArticleIDs,
    favoriteArticleIDs,
    setFavoriteArticleIDs,
  } = data
  const {
    setLoadingSources,
    loadingFeed,
    setLoadingFeed,
    loadingArticle,
    setLoadingArticle,
    setLoadingStatus,
    setSourcesError,
    feedError,
    setFeedError,
    articleError,
    setArticleError,
    setStatusError,
    feedCursor,
    setFeedCursor,
    hasMoreFeed,
    setHasMoreFeed,
    setNotice,
    setNowTick,
  } = request
  const {
    activeTab,
    readerView,
    setReaderView,
    showFloatingReader,
    setShowFloatingReader,
    selectedFeedBriefing,
    setSelectedFeedBriefing,
    unreadOnly,
    setUnreadOnly,
    favoriteOnly,
    setFavoriteOnly,
    keyword,
    setKeyword,
    tagFilter,
    setTagFilter,
    sourceFilter,
    setSourceFilter,
    mutedSiteKeys,
    setMutedSiteKeys,
    feedTitleOnlyMode,
    setFeedTitleOnlyMode,
    showFeedImages,
    setShowFeedImages,
    showFeedSearch,
    setShowFeedSearch,
    showAdvancedFilters,
    setShowAdvancedFilters,
    showFeedAIMoreMenu,
    setShowFeedAIMoreMenu,
    showManageModelPicker,
    setShowManageModelPicker,
    expandedThreadComments,
    setExpandedThreadComments,
    threadCommentsNewestFirst,
    setThreadCommentsNewestFirst,
    sourceProfileSource,
    setSourceProfileSource,
    sourceProfileTagPickerOpen,
    setSourceProfileTagPickerOpen,
    sourceProfileTagInput,
    setSourceProfileTagInput,
    pendingDeleteSource,
    setPendingDeleteSource,
  } = ui
  const {
    sourceGroupFilter,
    setSourceGroupFilter,
    setSidebarTagFilters,
    setSidebarTagFilterMode,
  } = sidebarState
  const {
    sourceContextMenu,
    closeSourceContextMenu,
  } = sourceContext
  const {
    sourceSiteKeyMap,
    sourceByID,
    mutedSiteSet,
    readArticleIDSet,
    favoriteArticleIDSet,
  } = sourcesIndex

  const {
    hasFeedBriefingEntry,
    visibleFeed,
    feedBriefingInsertIndex,
    feedBriefingNewArticleCount,
    readerStreamItems,
    selectedFeedIndex,
    unreadVisibleCount,
    favoriteVisibleCount,
    sourceFilterIDs,
    activeFeedBriefingSourceIDs,
    activeFeedBriefingKeyword,
    activeFeedBriefingTaskKey,
    activeFeedBriefingScopeLabel,
    visibleFeedArticleIDs,
    activeFeedBriefingAnchorArticleIDs,
    sourceFilterSelectValue,
    sourceFilterChipLabel,
    visibleSummaryTasks,
    summaryTaskStats,
    pendingArticleSummaryTasks,
    selectedSummaryTask,
    getSummaryTaskStatus,
    feedBriefingPreviewText,
    feedBriefingFreshnessLabel,
    hasActiveFilters,
    enabledSourceCount,
    unhealthySourceCount,
    threadComments,
    selectedArticleImageURL,
    selectedArticleReplyCountLabel,
    hasHiddenThreadComments,
    visibleThreadComments,
    detailMoreMenuRef,
    showDetailMoreMenu,
    closeDetailMoreMenu,
    toggleDetailMoreMenu,
    isThreadArticle,
    threadPrimaryBody,
    canTrackThread,
    canForceRecalcSummary,
    hasDetailMoreActions,
  } = useReaderFeatureDerived({
    activeTab,
    feed,
    summaryTasks,
    selectedArticle,
    selectedArticleID,
    selectedFeedBriefing,
    unreadOnly,
    favoriteOnly,
    keyword,
    tagFilter,
    sourceFilter,
    sourceGroupFilter,
    mutedSiteKeys,
    aiModel,
    feedBriefing,
    feedBriefingError,
    loadingFeedBriefing,
    feedBriefingGeneratedAt,
    feedBriefingAnchorArticleIDs,
    expandedThreadComments,
    threadCommentsNewestFirst,
    sources,
    sourceStatus,
    sourceByID,
    sourceSiteKeyMap,
    mutedSiteSet,
    readArticleIDSet,
    favoriteArticleIDSet,
    readerSources: sidebarState.readerSources,
  })

  const { loadCachedSummary, resolveSummaryTaskIdentity } = useSummaryArticleState({
    selectedSummaryTask,
    setArticleSummaryMeta,
    summaryRequestSeqRef,
    setArticleSummary,
    setArticleSummaryError,
    feed,
    selectedArticle,
    toErrorMessage,
  })

  const { upsertSummaryTask, removeSummaryTask, clearCompletedSummaryTasks } = useSummaryTaskActions({
    setSummaryTasks,
    summaryTaskNotifiedRef,
  })

  const {
    loadSources,
    loadStatus,
    refreshStatusIfVisible,
    loadFeed,
    cancelSidebarTagFeedReload,
    refreshAll,
    loadMore,
    pendingFeedCount,
    checkingFeedUpdates,
    applyPendingFeedUpdates,
  } = useReaderDataController({
    activeTab,
    feed,
    tagFilter,
    sourceFilter,
    keyword,
    feedCursor,
    loadingFeed,
    sourceByID,
    feedRequestSeqRef,
    sidebarTagFilterTimerRef,
    setLoadingSources,
    setSourcesError,
    setSources,
    setLoadingStatus,
    setStatusError,
    setSourceStatus,
    setLoadingFeed,
    setFeedError,
    setFeed,
    setFeedCursor,
    setHasMoreFeed,
    setNotice,
    parseSourceIDFilter,
    normalizeSourceKind,
    toErrorMessage,
  })

  const { startReaderSession, finalizeReaderSession, closeFloatingReader, openFeedBriefing } = useReaderSessionActions({
    readerSessionRef,
    setReadArticleIDs,
    upsertReadArticleID,
    readMarkMinScrollProgress,
    closeDetailMoreMenu,
    setShowFloatingReader,
    articleRequestSeqRef,
    summaryRequestSeqRef,
    setLoadingArticle,
    setArticleError,
    setSelectedArticle,
    setSelectedArticleID,
    setSelectedFeedBriefing,
    setArticleSummary,
    setArticleSummaryMeta,
    setArticleSummaryError,
    setLoadingArticleSummary,
    setExpandedThreadComments,
    setThreadCommentsNewestFirst,
    setReaderView,
    floatingDetailRef,
  })

  const {
    applyFeedBriefingSnapshot,
    saveFeedBriefingSnapshot,
    resetFeedBriefingState,
    onGenerateFeedBriefing,
  } = useFeedBriefingActions({
    activeFeedBriefingAnchorArticleIDs,
    activeFeedBriefingSourceIDs,
    activeFeedBriefingScopeLabel,
    activeFeedBriefingTaskKey,
    activeFeedBriefingKeyword,
    tagFilter,
    aiModel,
    setFeedBriefingTaskKey,
    setFeedBriefingScopeLabel,
    setFeedBriefingAnchorArticleIDs,
    setLoadingFeedBriefing,
    setFeedBriefingError,
    setFeedBriefing,
    setFeedBriefingItems,
    setFeedBriefingArticleCount,
    setFeedBriefingGeneratedAt,
    setFeedBriefingMeta,
    setSelectedFeedBriefing,
    setFeedBriefingSnapshots,
    setNotice,
    upsertSummaryTask,
    toErrorMessage,
  })

  const { openArticle, onSummarizeArticle, onTrackThread } = useReaderArticleActions({
    aiModel,
    selectedArticleID,
    sourceByID,
    readerSessionRef,
    articleRequestSeqRef,
    summaryRequestSeqRef,
    summaryTaskNotifiedRef,
    closeDetailMoreMenu,
    finalizeReaderSession,
    startReaderSession,
    loadCachedSummary,
    resolveSummaryTaskIdentity,
    upsertSummaryTask,
    setLoadingArticle,
    setReaderView,
    setShowFloatingReader,
    setArticleError,
    setSelectedFeedBriefing,
    setSelectedArticleID,
    setArticleSummary,
    setArticleSummaryMeta,
    setArticleSummaryError,
    setLoadingArticleSummary,
    setExpandedThreadComments,
    setThreadCommentsNewestFirst,
    setSelectedArticle,
    floatingDetailRef,
    setNotice,
    loadSources,
    refreshStatusIfVisible,
  })

  const { onOpenSummaryTask, onDismissSummaryTask } = useSummaryTaskStripActions({
    feedBriefingSnapshots,
    applyFeedBriefingSnapshot,
    setNotice,
    setActiveTab: ui.setActiveTab,
    openFeedBriefing,
    setReaderView,
    openArticle,
    removeSummaryTask,
  })

  const { openImmersiveReader, returnToReaderStream } = useReaderViewActions({
    streamScrollYRef,
    setReaderView,
    setShowFloatingReader,
    finalizeReaderSession,
  })

  const { applyFilters, clearFilters, removeFilter, onChangeAIModel, toggleSiteMuted } = useReaderFilterControls({
    aiModel,
    setAIModel,
    selectedArticleID,
    summaryRequestSeqRef,
    loadCachedSummary,
    resetFeedBriefingState,
    cancelSidebarTagFeedReload,
    loadFeed,
    setKeyword,
    setTagFilter,
    setSourceFilter,
    setUnreadOnly,
    setFavoriteOnly,
    setSourceGroupFilter,
    setSidebarTagFilters,
    setSidebarTagFilterMode,
    setMutedSiteKeys,
    setSelectedArticle,
    setSelectedArticleID,
    setFeedCursor,
    setShowManageModelPicker,
    setArticleSummary,
    setArticleSummaryMeta,
    setArticleSummaryError,
    setNotice,
  })

  const onToggleFavoriteArticle = useCallback(
    (articleID: number) => {
      setFavoriteArticleIDs((previous) => toggleFavoriteArticleID(previous, articleID))
    },
    [setFavoriteArticleIDs],
  )

  const isFavoriteArticle = Boolean(selectedArticleID && favoriteArticleIDSet.has(selectedArticleID))

  const {
    applySourceFilterFromSidebar,
    registerSidebarSourceItemRef,
    applySidebarTagFilters,
    toggleSidebarTagFilter,
    switchSidebarTagFilterMode,
    openSourceProfile,
    openDeleteSourceConfirm,
  } = useReaderSidebarControls({
    cancelSidebarTagFeedReload,
    resetFeedBriefingState,
    sidebarState,
    setSourceFilter,
    setSelectedArticle,
    setSelectedArticleID,
    setFeedCursor,
    loadFeed,
    sidebarSourceItemRefs,
    sourceTagList,
    closeSourceContextMenu,
    setSourceProfileSource,
    setSourceProfileTagPickerOpen,
    setSourceProfileTagInput,
    setPendingDeleteSource,
  })

  useReaderFeatureEffects({
    aiModel,
    readArticleIDs,
    favoriteArticleIDs,
    maxStoredReadArticles,
    maxStoredFavoriteArticles,
    setSummaryTasks,
    summaryTaskNotifiedRef,
    pendingArticleSummaryTasks,
    resolveSummaryTaskIdentity,
    selectedArticleID,
    upsertSummaryTask,
    setArticleSummary,
    setArticleSummaryMeta,
    setArticleSummaryError,
    setNotice: (notice) => setNotice(notice),
    activeTab,
    loadingFeed,
    loadingFeedBriefing,
    activeFeedBriefingAnchorArticleIDs,
    hasFeedBriefingEntry,
    feedBriefingTaskKey,
    activeFeedBriefingTaskKey,
    feedBriefingSnapshots,
    applyFeedBriefingSnapshot,
    activeFeedBriefingKeyword,
    tagFilter,
    activeFeedBriefingSourceIDs,
    activeFeedBriefingScopeLabel,
    saveFeedBriefingSnapshot,
    feedBriefingCacheAttemptedRef,
    hasMoreFeed,
    feedCursor,
    feedAutoLoadRef,
    feedAutoLoadCooldownRef,
    loadMore,
    setNowTick,
    readerView,
    showFloatingReader,
    floatingDetailRef,
    closeFloatingReader,
    readerSessionRef,
    sourceProfileSource,
    sourceContextMenu,
    pendingDeleteSource,
    showFeedAIMoreMenu,
    showDetailMoreMenu,
    setSourceProfileSource,
    closeSourceContextMenu,
    setPendingDeleteSource,
    setShowFeedAIMoreMenu,
    closeDetailMoreMenu,
    readerStreamItems,
    selectedFeedIndex,
    selectedArticleLink: selectedArticle?.link,
    openArticle,
    openFeedBriefing,
  })

  return {
    hasFeedBriefingEntry,
    visibleFeed,
    feedBriefingInsertIndex,
    feedBriefingNewArticleCount,
    readerStreamItems,
    selectedFeedIndex,
    unreadVisibleCount,
    favoriteVisibleCount,
    sourceFilterIDs,
    activeFeedBriefingSourceIDs,
    activeFeedBriefingKeyword,
    activeFeedBriefingTaskKey,
    activeFeedBriefingScopeLabel,
    visibleFeedArticleIDs,
    activeFeedBriefingAnchorArticleIDs,
    sourceFilterSelectValue,
    sourceFilterChipLabel,
    visibleSummaryTasks,
    summaryTaskStats,
    selectedSummaryTask,
    getSummaryTaskStatus,
    feedBriefingPreviewText,
    feedBriefingFreshnessLabel,
    hasActiveFilters,
    enabledSourceCount,
    unhealthySourceCount,
    threadComments,
    selectedArticleImageURL,
    selectedArticleReplyCountLabel,
    hasHiddenThreadComments,
    visibleThreadComments,
    detailMoreMenuRef,
    showDetailMoreMenu,
    closeDetailMoreMenu,
    toggleDetailMoreMenu,
    isThreadArticle,
    threadPrimaryBody,
    canTrackThread,
    canForceRecalcSummary,
    hasDetailMoreActions,
    isFavoriteArticle,
    clearCompletedSummaryTasks,
    loadSources,
    loadStatus,
    refreshStatusIfVisible,
    loadFeed,
    cancelSidebarTagFeedReload,
    refreshAll,
    loadMore,
    pendingFeedCount,
    checkingFeedUpdates,
    applyPendingFeedUpdates,
    applyFeedBriefingSnapshot,
    onGenerateFeedBriefing,
    openArticle,
    onToggleFavoriteArticle,
    onSummarizeArticle,
    onTrackThread,
    onOpenSummaryTask,
    onDismissSummaryTask,
    openImmersiveReader,
    returnToReaderStream,
    applyFilters,
    clearFilters,
    removeFilter,
    onChangeAIModel,
    toggleSiteMuted,
    applySourceFilterFromSidebar,
    registerSidebarSourceItemRef,
    applySidebarTagFilters,
    toggleSidebarTagFilter,
    switchSidebarTagFilterMode,
    openSourceProfile,
    openDeleteSourceConfirm,
    closeFloatingReader,
    openFeedBriefing,
    finalizeReaderSession,
    articleSummary,
    articleSummaryMeta,
    articleSummaryError,
    loadingArticleSummary,
    loadingArticle,
    articleError,
    buildCompactTitleParts,
    formatTimeAgo,
    formatTimeAgoCompact,
    formatReplyCount,
    normalizeImageURL,
    plainText,
    truncate,
    feedBriefingMeta,
    feedBriefingError,
    feedBriefing,
    loadingFeedBriefing,
    feedBriefingItems,
    feedBriefingArticleCount,
    feedBriefingScopeLabel,
    aiModel,
    threadCommentsNewestFirst,
    setThreadCommentsNewestFirst,
    expandedThreadComments,
    setExpandedThreadComments,
    feedTitleOnlyMode,
    showFeedImages,
    showFeedSearch,
    showAdvancedFilters,
    showFeedAIMoreMenu,
    setShowFeedAIMoreMenu,
    selectedArticle,
    selectedArticleID,
    selectedFeedBriefing,
    hasMoreFeed,
    loadingFeed,
    feedError,
    feed,
    readArticleIDSet,
    favoriteArticleIDSet,
    feedAIMoreRef,
    feedAutoLoadRef,
    keyword,
    tagFilter,
    mutedSiteKeys,
    sourceFilter,
    unreadOnly,
    favoriteOnly,
    setUnreadOnly,
    setFavoriteOnly,
    setKeyword,
    setTagFilter,
    setSourceFilter,
    setFeedTitleOnlyMode,
    setShowFeedImages,
    setShowFeedSearch,
    setShowAdvancedFilters,
    setSourceGroupFilter,
    setSidebarTagFilters,
    showFloatingReader,
    readerView,
    floatingDetailRef,
    sourceProfileSource,
    sourceProfileTagPickerOpen,
    setSourceProfileTagPickerOpen,
    sourceProfileTagInput,
    setSourceProfileTagInput,
    pendingDeleteSource,
    setPendingDeleteSource,
    setSourceProfileSource,
    showManageModelPicker,
    setShowManageModelPicker,
  }
}
