import type { AppStateData } from './use-app-state-data'
import type { AppStateRefs } from './use-app-state-refs'
import type { AppStateRequest } from './use-app-state-request'
import type { AppStateUI } from './use-app-state-ui'
import type { ReaderSidebarState } from './use-reader-sidebar-state'
import type { SourceContextMenuController } from './use-source-context-menu'
import type { SourcesIndex } from './use-sources-index'
import { useReaderFeatureActions } from './use-reader-feature-actions'
import { useReaderFeatureDerived } from './use-reader-feature-derived'
import { useReaderFeatureEffects } from './use-reader-feature-effects'
import {
  buildCompactTitleParts,
  formatReplyCount,
  formatTimeAgo,
  formatTimeAgoCompact,
  maxStoredFavoriteArticles,
  maxStoredReadArticles,
  normalizeImageURL,
  plainText,
  truncate,
} from '../lib/app-utils'

type UseReaderFeatureSectionParams = {
  refs: AppStateRefs
  data: AppStateData
  request: AppStateRequest
  ui: AppStateUI
  sidebarState: ReaderSidebarState
  sourcesIndex: SourcesIndex
  sourceContext: SourceContextMenuController
}

export function useReaderFeatureSection({
  refs,
  data,
  request,
  ui,
  sidebarState,
  sourcesIndex,
  sourceContext,
}: UseReaderFeatureSectionParams) {
  const {
    floatingDetailRef,
    feedAIMoreRef,
    feedBriefingCacheAttemptedRef,
    feedAutoLoadRef,
    feedAutoLoadCooldownRef,
    summaryTaskNotifiedRef,
    readerSessionRef,
  } = refs
  const {
    sources,
    feed,
    selectedArticle,
    selectedArticleID,
    articleSummary,
    setArticleSummary,
    articleSummaryMeta,
    setArticleSummaryMeta,
    summaryTasks,
    setSummaryTasks,
    loadingArticleSummary,
    articleSummaryError,
    setArticleSummaryError,
    feedBriefing,
    feedBriefingMeta,
    feedBriefingItems,
    feedBriefingArticleCount,
    feedBriefingScopeLabel,
    feedBriefingGeneratedAt,
    feedBriefingAnchorArticleIDs,
    feedBriefingTaskKey,
    feedBriefingSnapshots,
    loadingFeedBriefing,
    feedBriefingError,
    aiModel,
    sourceStatus,
    readArticleIDs,
    favoriteArticleIDs,
  } = data
  const {
    loadingFeed,
    loadingArticle,
    feedError,
    articleError,
    feedCursor,
    hasMoreFeed,
    setNotice,
    setNowTick,
  } = request
  const {
    activeTab,
    readerView,
    showFloatingReader,
    selectedFeedBriefing,
    unreadOnly,
    setUnreadOnly,
    favoriteOnly,
    setFavoriteOnly,
    keyword,
    setKeyword,
    tagFilter,
    setTagFilter,
    sourceFilter,
    setSourceFilter,
    mutedSiteKeys,
    feedTitleOnlyMode,
    setFeedTitleOnlyMode,
    showFeedImages,
    setShowFeedImages,
    showFeedSearch,
    setShowFeedSearch,
    showAdvancedFilters,
    setShowAdvancedFilters,
    showFeedAIMoreMenu,
    setShowFeedAIMoreMenu,
    showManageModelPicker,
    setShowManageModelPicker,
    expandedThreadComments,
    setExpandedThreadComments,
    threadCommentsNewestFirst,
    setThreadCommentsNewestFirst,
    sourceProfileSource,
    setSourceProfileSource,
    sourceProfileTagPickerOpen,
    setSourceProfileTagPickerOpen,
    sourceProfileTagInput,
    setSourceProfileTagInput,
    pendingDeleteSource,
    setPendingDeleteSource,
  } = ui
  const {
    sourceGroupFilter,
    setSourceGroupFilter,
    setSidebarTagFilters,
  } = sidebarState
  const {
    sourceContextMenu,
    closeSourceContextMenu,
  } = sourceContext
  const {
    sourceSiteKeyMap,
    sourceByID,
    mutedSiteSet,
    readArticleIDSet,
    favoriteArticleIDSet,
  } = sourcesIndex

  const derived = useReaderFeatureDerived({
    activeTab,
    feed,
    summaryTasks,
    selectedArticle,
    selectedArticleID,
    selectedFeedBriefing,
    unreadOnly,
    favoriteOnly,
    keyword,
    tagFilter,
    sourceFilter,
    sourceGroupFilter,
    mutedSiteKeys,
    aiModel,
    feedBriefing,
    feedBriefingError,
    loadingFeedBriefing,
    feedBriefingGeneratedAt,
    feedBriefingAnchorArticleIDs,
    expandedThreadComments,
    threadCommentsNewestFirst,
    sources,
    sourceStatus,
    sourceByID,
    sourceSiteKeyMap,
    mutedSiteSet,
    readArticleIDSet,
    favoriteArticleIDSet,
    readerSources: sidebarState.readerSources,
  })

  const {
    hasFeedBriefingEntry,
    visibleFeed,
    feedBriefingInsertIndex,
    feedBriefingNewArticleCount,
    readerStreamItems,
    selectedFeedIndex,
    unreadVisibleCount,
    favoriteVisibleCount,
    sourceFilterIDs,
    activeFeedBriefingSourceIDs,
    activeFeedBriefingKeyword,
    activeFeedBriefingTaskKey,
    activeFeedBriefingScopeLabel,
    visibleFeedArticleIDs,
    activeFeedBriefingAnchorArticleIDs,
    sourceFilterSelectValue,
    sourceFilterChipLabel,
    visibleSummaryTasks,
    summaryTaskStats,
    pendingArticleSummaryTasks,
    selectedSummaryTask,
    getSummaryTaskStatus,
    feedBriefingPreviewText,
    feedBriefingFreshnessLabel,
    hasActiveFilters,
    enabledSourceCount,
    unhealthySourceCount,
    threadComments,
    selectedArticleImageURL,
    selectedArticleReplyCountLabel,
    hasHiddenThreadComments,
    visibleThreadComments,
    detailMoreMenuRef,
    showDetailMoreMenu,
    closeDetailMoreMenu,
    toggleDetailMoreMenu,
    isThreadArticle,
    threadPrimaryBody,
    canTrackThread,
    canForceRecalcSummary,
    hasDetailMoreActions,
  } = derived

  const {
    resolveSummaryTaskIdentity,
    upsertSummaryTask,
    clearCompletedSummaryTasks,
    loadSources,
    loadStatus,
    refreshStatusIfVisible,
    loadFeed,
    cancelSidebarTagFeedReload,
    refreshAll,
    loadMore,
    pendingFeedCount,
    checkingFeedUpdates,
    applyPendingFeedUpdates,
    applyFeedBriefingSnapshot,
    saveFeedBriefingSnapshot,
    onGenerateFeedBriefing,
    openArticle,
    onToggleFavoriteArticle,
    isFavoriteArticle,
    onSummarizeArticle,
    onTrackThread,
    onOpenSummaryTask,
    onDismissSummaryTask,
    openImmersiveReader,
    returnToReaderStream,
    applyFilters,
    clearFilters,
    removeFilter,
    onChangeAIModel,
    toggleSiteMuted,
    applySourceFilterFromSidebar,
    applySourceGroupFilterFromSidebar,
    registerSidebarSourceItemRef,
    applySidebarTagFilters,
    toggleSidebarTagFilter,
    switchSidebarTagFilterMode,
    openSourceProfile,
    openDeleteSourceConfirm,
    closeFloatingReader,
    openFeedBriefing,
    finalizeReaderSession,
  } = useReaderFeatureActions({
    refs,
    data,
    request,
    ui,
    sidebarState,
    sourcesIndex,
    sourceContext,
    derived,
  })

  useReaderFeatureEffects({
    aiModel,
    readArticleIDs,
    favoriteArticleIDs,
    maxStoredReadArticles,
    maxStoredFavoriteArticles,
    setSummaryTasks,
    summaryTaskNotifiedRef,
    pendingArticleSummaryTasks,
    resolveSummaryTaskIdentity,
    selectedArticleID,
    upsertSummaryTask,
    setArticleSummary,
    setArticleSummaryMeta,
    setArticleSummaryError,
    setNotice: (notice) => setNotice(notice),
    activeTab,
    unreadOnly,
    favoriteOnly,
    loadingFeed,
    loadingFeedBriefing,
    activeFeedBriefingAnchorArticleIDs,
    hasFeedBriefingEntry,
    feedBriefingTaskKey,
    activeFeedBriefingTaskKey,
    feedBriefingSnapshots,
    applyFeedBriefingSnapshot,
    activeFeedBriefingKeyword,
    tagFilter,
    activeFeedBriefingSourceIDs,
    activeFeedBriefingScopeLabel,
    saveFeedBriefingSnapshot,
    feedBriefingCacheAttemptedRef,
    hasMoreFeed,
    feedCursor,
    feedAutoLoadRef,
    feedAutoLoadCooldownRef,
    loadMore,
    setNowTick,
    readerView,
    showFloatingReader,
    floatingDetailRef,
    closeFloatingReader,
    readerSessionRef,
    sourceProfileSource,
    sourceContextMenu,
    pendingDeleteSource,
    showFeedAIMoreMenu,
    showDetailMoreMenu,
    setSourceProfileSource,
    closeSourceContextMenu,
    setPendingDeleteSource,
    setShowFeedAIMoreMenu,
    closeDetailMoreMenu,
    readerStreamItems,
    selectedFeedIndex,
    selectedArticleLink: selectedArticle?.link,
    openArticle,
    openFeedBriefing,
  })

  return {
    hasFeedBriefingEntry,
    visibleFeed,
    feedBriefingInsertIndex,
    feedBriefingNewArticleCount,
    readerStreamItems,
    selectedFeedIndex,
    unreadVisibleCount,
    favoriteVisibleCount,
    sourceFilterIDs,
    activeFeedBriefingSourceIDs,
    activeFeedBriefingKeyword,
    activeFeedBriefingTaskKey,
    activeFeedBriefingScopeLabel,
    visibleFeedArticleIDs,
    activeFeedBriefingAnchorArticleIDs,
    sourceFilterSelectValue,
    sourceFilterChipLabel,
    visibleSummaryTasks,
    summaryTaskStats,
    selectedSummaryTask,
    getSummaryTaskStatus,
    feedBriefingPreviewText,
    feedBriefingFreshnessLabel,
    hasActiveFilters,
    enabledSourceCount,
    unhealthySourceCount,
    threadComments,
    selectedArticleImageURL,
    selectedArticleReplyCountLabel,
    hasHiddenThreadComments,
    visibleThreadComments,
    detailMoreMenuRef,
    showDetailMoreMenu,
    closeDetailMoreMenu,
    toggleDetailMoreMenu,
    isThreadArticle,
    threadPrimaryBody,
    canTrackThread,
    canForceRecalcSummary,
    hasDetailMoreActions,
    isFavoriteArticle,
    clearCompletedSummaryTasks,
    loadSources,
    loadStatus,
    refreshStatusIfVisible,
    loadFeed,
    cancelSidebarTagFeedReload,
    refreshAll,
    loadMore,
    pendingFeedCount,
    checkingFeedUpdates,
    applyPendingFeedUpdates,
    applyFeedBriefingSnapshot,
    onGenerateFeedBriefing,
    openArticle,
    onToggleFavoriteArticle,
    onSummarizeArticle,
    onTrackThread,
    onOpenSummaryTask,
    onDismissSummaryTask,
    openImmersiveReader,
    returnToReaderStream,
    applyFilters,
    clearFilters,
    removeFilter,
    onChangeAIModel,
    toggleSiteMuted,
    applySourceFilterFromSidebar,
    applySourceGroupFilterFromSidebar,
    registerSidebarSourceItemRef,
    applySidebarTagFilters,
    toggleSidebarTagFilter,
    switchSidebarTagFilterMode,
    openSourceProfile,
    openDeleteSourceConfirm,
    closeFloatingReader,
    openFeedBriefing,
    finalizeReaderSession,
    articleSummary,
    articleSummaryMeta,
    articleSummaryError,
    loadingArticleSummary,
    loadingArticle,
    articleError,
    buildCompactTitleParts,
    formatTimeAgo,
    formatTimeAgoCompact,
    formatReplyCount,
    normalizeImageURL,
    plainText,
    truncate,
    feedBriefingMeta,
    feedBriefingError,
    feedBriefing,
    loadingFeedBriefing,
    feedBriefingItems,
    feedBriefingArticleCount,
    feedBriefingScopeLabel,
    aiModel,
    threadCommentsNewestFirst,
    setThreadCommentsNewestFirst,
    expandedThreadComments,
    setExpandedThreadComments,
    feedTitleOnlyMode,
    showFeedImages,
    showFeedSearch,
    showAdvancedFilters,
    showFeedAIMoreMenu,
    setShowFeedAIMoreMenu,
    selectedArticle,
    selectedArticleID,
    selectedFeedBriefing,
    hasMoreFeed,
    loadingFeed,
    feedError,
    feed,
    readArticleIDSet,
    favoriteArticleIDSet,
    feedAIMoreRef,
    feedAutoLoadRef,
    keyword,
    tagFilter,
    mutedSiteKeys,
    sourceFilter,
    unreadOnly,
    favoriteOnly,
    setUnreadOnly,
    setFavoriteOnly,
    setKeyword,
    setTagFilter,
    setSourceFilter,
    setFeedTitleOnlyMode,
    setShowFeedImages,
    setShowFeedSearch,
    setShowAdvancedFilters,
    setSourceGroupFilter,
    setSidebarTagFilters,
    showFloatingReader,
    readerView,
    floatingDetailRef,
    sourceProfileSource,
    sourceProfileTagPickerOpen,
    setSourceProfileTagPickerOpen,
    sourceProfileTagInput,
    setSourceProfileTagInput,
    pendingDeleteSource,
    setPendingDeleteSource,
    setSourceProfileSource,
    showManageModelPicker,
    setShowManageModelPicker,
  }
}
