import type { SourceContextMenuController } from './use-source-context-menu'
import type { ReaderSidebarState } from './use-reader-sidebar-state'
import type { SourcesIndex } from './use-sources-index'
import { useReaderWorkspaceProps } from './use-reader-workspace-props'
import { useReaderWorkspaceSidebarProps } from './use-reader-workspace-sidebar-props'
import { useReaderWorkspaceFeedProps } from './use-reader-workspace-feed-props'
import { useReaderWorkspaceDetailProps } from './use-reader-workspace-detail-props'
import type { useReaderFeatureSection } from './use-reader-feature-section'
import { summaryTaskStatusLabel } from '../lib/summary-task-utils'
import { threadPreviewCommentLimit, sidebarTagCollapseCount } from '../lib/app-domain'

type UseReaderWorkspaceCompositionParams = {
  sidebarState: ReaderSidebarState
  readerSection: ReturnType<typeof useReaderFeatureSection>
  availableTags: SourcesIndex['availableTags']
  onOpenSourceContextMenu: SourceContextMenuController['openSourceContextMenu']
  onOpenSourceContextMenuAt: SourceContextMenuController['openSourceContextMenuAt']
  returnToAILibrary?: () => void
  returnToAILibraryLabel?: string
}

export function useReaderWorkspaceComposition({
  sidebarState,
  readerSection,
  availableTags,
  onOpenSourceContextMenu,
  onOpenSourceContextMenuAt,
  returnToAILibrary,
  returnToAILibraryLabel,
}: UseReaderWorkspaceCompositionParams) {
  const {
    sourceGroupFilter,
    sidebarTagFilters,
    sidebarTagFilterMode,
    showAllSidebarTags,
    showSubscriptionSidebar,
    showTrackedSidebar,
    showAllTrackedSidebar,
    readerTrackedSources,
    readerSources,
    visibleTrackedSidebarSources,
    hasMoreTrackedSidebarSources,
    sourceGroups,
    sidebarTagFilterSet,
    sidebarVisibleFeedSources,
    setShowSubscriptionSidebar,
    setShowAllSidebarTags,
    setShowTrackedSidebar,
    setShowAllTrackedSidebar,
  } = sidebarState

  const {
    sourceFilter,
    applySourceFilterFromSidebar,
    applySourceGroupFilterFromSidebar,
    switchSidebarTagFilterMode,
    applySidebarTagFilters,
    toggleSidebarTagFilter,
    registerSidebarSourceItemRef,
    showFloatingReader,
    readerView,
    feedTitleOnlyMode,
    showFeedImages,
    showFeedSearch,
    showAdvancedFilters,
    showFeedAIMoreMenu,
    loadingFeedBriefing,
    unreadVisibleCount,
    favoriteVisibleCount,
    unreadOnly,
    favoriteOnly,
    hasActiveFilters,
    keyword,
    tagFilter,
    mutedSiteKeys,
    sourceFilterSelectValue,
    sourceFilterChipLabel,
    loadingFeed,
    feedError,
    feed,
    visibleFeed,
    hasFeedBriefingEntry,
    feedBriefingInsertIndex,
    selectedArticleID,
    selectedFeedBriefing,
    readArticleIDSet,
    favoriteArticleIDSet,
    feedAIMoreRef,
    feedAutoLoadRef,
    hasMoreFeed,
    feedBriefingPreviewText,
    feedBriefingScopeLabel,
    feedBriefingFreshnessLabel,
    feedBriefingNewArticleCount,
    feedBriefingArticleCount,
    feedBriefingItems,
    onGenerateFeedBriefing,
    setUnreadOnly,
    setFavoriteOnly,
    applyFilters,
    setKeyword,
    setTagFilter,
    clearFilters,
    removeFilter,
    loadFeed,
    openArticle,
    onToggleFavoriteArticle,
    openFeedBriefing,
    loadMore,
    normalizeImageURL,
    formatTimeAgo,
    formatTimeAgoCompact,
    formatReplyCount,
    buildCompactTitleParts,
    plainText,
    truncate,
    getSummaryTaskStatus,
    setShowFeedAIMoreMenu,
    setFeedTitleOnlyMode,
    setShowFeedImages,
    setShowFeedSearch,
    setShowAdvancedFilters,
    setSourceGroupFilter,
    setSidebarTagFilters,
    setSourceFilter,
    floatingDetailRef,
    selectedArticle,
    loadingArticle,
    articleError,
    returnToReaderStream,
    closeFloatingReader,
    openImmersiveReader,
    aiModel,
    feedBriefingMeta,
    feedBriefingError,
    feedBriefing,
    selectedArticleReplyCountLabel,
    selectedArticleImageURL,
    closeDetailMoreMenu,
    isFavoriteArticle,
    onSummarizeArticle,
    loadingArticleSummary,
    hasDetailMoreActions,
    detailMoreMenuRef,
    showDetailMoreMenu,
    toggleDetailMoreMenu,
    canTrackThread,
    onTrackThread,
    canForceRecalcSummary,
    articleSummaryError,
    articleSummary,
    articleSummaryMeta,
    selectedSummaryTask,
    isThreadArticle,
    threadPrimaryBody,
    visibleThreadComments,
    threadComments,
    threadCommentsNewestFirst,
    expandedThreadComments,
    hasHiddenThreadComments,
    setThreadCommentsNewestFirst,
    setExpandedThreadComments,
  } = readerSection

  const readerSidebarProps = useReaderWorkspaceSidebarProps({
    showSubscriptionSidebar,
    sourceFilter,
    readerSources,
    sourceGroups,
    sidebarTagFilterMode,
    sidebarTagFilters,
    sidebarTagFilterSet,
    showAllSidebarTags,
    sidebarTagCollapseCount,
    sidebarVisibleFeedSources,
    sourceGroupFilterKey: sourceGroupFilter?.key ?? '',
    isSourceGroupFilterActive: Boolean(sourceGroupFilter),
    readerTrackedSources,
    showTrackedSidebar,
    visibleTrackedSidebarSources,
    hasMoreTrackedSidebarSources,
    showAllTrackedSidebar,
    onApplySourceFilterFromSidebar: applySourceFilterFromSidebar,
    onApplySourceGroupFilterFromSidebar: applySourceGroupFilterFromSidebar,
    onSwitchSidebarTagFilterMode: switchSidebarTagFilterMode,
    onApplySidebarTagFilters: applySidebarTagFilters,
    onToggleSidebarTagFilter: toggleSidebarTagFilter,
    onRegisterSidebarSourceItemRef: registerSidebarSourceItemRef,
    onOpenSourceContextMenu,
    onOpenSourceContextMenuAt,
    setShowSubscriptionSidebar,
    setShowAllSidebarTags,
    setShowTrackedSidebar,
    setShowAllTrackedSidebar,
  })

  const readerFeedProps = useReaderWorkspaceFeedProps({
    showFloatingReader,
    readerView,
    feedTitleOnlyMode,
    showFeedImages,
    showFeedSearch,
    showAdvancedFilters,
    showFeedAIMoreMenu,
    loadingFeedBriefing,
    unreadVisibleCount,
    favoriteVisibleCount,
    unreadOnly,
    favoriteOnly,
    hasActiveFilters: Boolean(hasActiveFilters),
    keyword,
    tagFilter,
    sourceFilter,
    mutedSiteKeys,
    availableTags,
    readerSources,
    sourceFilterSelectValue,
    sourceFilterChipLabel,
    loadingFeed,
    feedError,
    feed,
    visibleFeed,
    hasFeedBriefingEntry,
    feedBriefingInsertIndex,
    selectedArticleID,
    selectedFeedBriefing,
    readArticleIDSet,
    favoriteArticleIDSet,
    feedAIMoreRef,
    feedAutoLoadRef,
    hasMoreFeed,
    feedBriefingPreviewText,
    feedBriefingScopeLabel,
    feedBriefingFreshnessLabel,
    feedBriefingNewArticleCount,
    feedBriefingArticleCount,
    feedBriefingItems,
    onGenerateFeedBriefing,
    onSetUnreadOnly: setUnreadOnly,
    onSetFavoriteOnly: setFavoriteOnly,
    onApplyFilters: applyFilters,
    onChangeKeyword: setKeyword,
    onChangeTagFilter: setTagFilter,
    onClearFilters: clearFilters,
    onRemoveFilter: removeFilter,
    onRetryLoadFeed: () => loadFeed(false),
    onOpenArticle: openArticle,
    onToggleFavoriteArticle,
    onOpenFeedBriefing: openFeedBriefing,
    onLoadMore: loadMore,
    normalizeImageURL,
    formatTimeAgo,
    formatTimeAgoCompact,
    formatReplyCount,
    buildCompactTitleParts,
    plainText,
    truncate,
    getSummaryTaskStatus,
    summaryTaskStatusLabel,
    setShowFeedAIMoreMenu,
    setFeedTitleOnlyMode,
    setShowFeedImages,
    setShowFeedSearch,
    setShowAdvancedFilters,
    setSourceGroupFilter,
    setSidebarTagFilters,
    setSourceFilter,
  })

  const readerDetailProps = useReaderWorkspaceDetailProps({
    floatingDetailRef,
    showFloatingReader,
    readerView,
    selectedArticle,
    selectedFeedBriefing,
    loadingArticle,
    articleError,
    selectedArticleID,
    onOpenArticle: openArticle,
    feedBriefingScopeLabel,
    feedBriefingFreshnessLabel,
    returnToReaderStream,
    returnToAILibrary,
    returnToAILibraryLabel,
    closeFloatingReader,
    openImmersiveReader,
    aiModel,
    onGenerateFeedBriefing,
    loadingFeedBriefing,
    feedBriefingMeta,
    feedBriefingNewArticleCount,
    feedBriefingError,
    feedBriefing,
    feedBriefingItems,
    feedBriefingArticleCount,
    formatTimeAgo,
    selectedArticleReplyCountLabel,
    selectedArticleImageURL,
    closeDetailMoreMenu,
    isFavoriteArticle,
    onToggleFavoriteArticle,
    onSummarizeArticle,
    loadingArticleSummary,
    hasDetailMoreActions,
    detailMoreMenuRef,
    showDetailMoreMenu,
    toggleDetailMoreMenu,
    canTrackThread,
    onTrackThread,
    canForceRecalcSummary,
    articleSummaryError,
    articleSummary,
    articleSummaryMeta,
    selectedSummaryTask,
    isThreadArticle,
    threadPrimaryBody,
    visibleThreadComments,
    threadComments,
    threadCommentsNewestFirst,
    threadPreviewCommentLimit,
    expandedThreadComments,
    hasHiddenThreadComments,
    setThreadCommentsNewestFirst,
    setExpandedThreadComments,
  })

  const readerWorkspaceProps = useReaderWorkspaceProps({
    showSubscriptionSidebar,
    setShowSubscriptionSidebar,
    sidebarProps: readerSidebarProps,
    feedProps: readerFeedProps,
    showFloatingReader,
    readerView,
    detailProps: readerDetailProps,
  })

  return {
    readerWorkspaceProps,
  }
}
